### PR TITLE
Support T2 chips in recovery mode

### PR DESCRIPTION
**Pull request by rickmark**

### CODE REVIEW

**Comment by nikias** [comment]
Question: you say "recovery mode" yet you add it to usbmuxd, is it speaking usbmux protocol in this state?

**Comment by nikias** [comment]
@rickmark I think it might be restore mode actually, could that be? I don't have a mac with T2 chip so I can't test this :)

**Comment by rickmark** [comment]
During the restore process it boots a version of iOS with the usbmuxd service of "com.apple.mobile.restored" as part of the restore.  So yes, even a device that is "restoring" needs usbmuxd to complete the process...

**Comment by nikias** [comment]
Ok that's what we call restore mode :)

**Comment by rickmark** [comment]
> Ok that's what we call restore mode :)

Sorry for the term difference.  This is in concert with these other PRs:

https://github.com/libimobiledevice/idevicerestore/pull/300
https://github.com/libimobiledevice/libirecovery/pull/55

**Comment by nikias** [comment]
I merged it with one commit and a more precise commit message.

**Pull request closed without merging**
